
version: 2

sources:
  - name: survey-cto
    schema: public
    database: postgres
    tables:
      - name: delhi
        identifier: delhi_india_measurement_form_2022
        description: One record per form data. Includes duplicates and modified data.
       
models:
  - name: delhi_india
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
           
  - name: delete_duplicates
    description: "Deduped model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

