
models:
  - name: int_classroom_surveys_delhi
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: tamil_nadu
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 

  
  - name: karnataka
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 
  
    
  - name: indonesia
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 
  
  - name: uganda
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 
  
           